Siralex214/update about
onRuntime/onruntime-website pull request #39
Opened 2022-11-28 19:11 UTC by siralex214

2022-11-28 23:31 UTC, AntoineKM reviewed
Younès B. - Lead Developer
Marah M. - Junior CM
Inès M. - Senior CM
Alois G. - Lead CM
Lucas B. - Admin & Designer
Killian M. - Admin & Product Owner
Jeremy B. - Admin & Developer
Antoine K. - Admin & Developer

2022-11-30 18:12 UTC, AntoineKM approved these changes

2022-11-30 18:12 UTC, AntoineKM commented
@siralex214 we remove the draft mode ?

2022-12-09 13:50 UTC, jerembdn requested changes

2022-12-09 13:50 UTC, jerembdn commented on src/data/members.ts
>    },
You forgot Alois :(

2022-12-09 14:12 UTC, jerembdn commented on src/data/members.ts
>    },
ahok

2022-12-09 14:12 UTC, jerembdn approved these changes

2022-12-09 14:13 UTC, jerembdn commented
Can you rebase on the base branch ?

2022-12-10 06:34 UTC, merged